### ISSUE TITLE
雷电3接口接显卡扩展坞有测试么？

### ISSUE THREAD

**Issue by jd04063221** [cloudlang/DELL-XPS-15-9570-8750H-1080P-macOS-Mojave#1]
雷电3接口接显卡扩展坞有测试么？雷电3接口能被驱动么？

谢谢！

**Comment by imsancn** [comment]
> 雷电3接口接显卡扩展坞有测试么？雷电3接口能被驱动么？
> 
> 谢谢！
我目前是typc 转mini dp外接的4k显示器正常
